# Generated by Django 5.2.4 on 2025-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('orcid', models.CharField(blank=True, max_length=100)),
                ('social_media_profile', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='author_pics/')),
                ('bene_id', models.CharField(blank=True, help_text='Beneficiary ID from Cashfree', max_length=100, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('is_author_of_the_month', models.BooleanField(default=False)),
                ('is_author_of_the_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('designation', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for the current, active record.', null=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BindingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(max_length=100)),
                ('min_pages', models.PositiveIntegerField(default=1)),
                ('max_pages', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_thickness_mm', models.DecimalField(decimal_places=2, default=0.5, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('pages', models.IntegerField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_book_of_the_month', models.BooleanField(default=False)),
                ('is_book_of_the_year', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('binding_type', models.CharField(max_length=100)),
                ('weight_grams', models.PositiveIntegerField()),
                ('length_mm', models.PositiveIntegerField()),
                ('width_mm', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0, help_text='Quantity on hand')),
            ],
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_additional_images/')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BookParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('author', 'Author'), ('editor', 'Editor')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the chapter in the book')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChapterContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='The order of the contributor within this chapter')),
                ('designation_at_publication', models.CharField(blank=True, max_length=255)),
                ('organization_at_publication', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PaperQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 70GSM, 80GSM Matte, Colored', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Paper qualities',
            },
        ),
        migrations.CreateModel(
            name='PaperSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., A4, A5, 8x10', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerPageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_mm', models.DecimalField(decimal_places=2, default=0.1, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp_multiplier', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('nature_of_publication', models.CharField(blank=True, max_length=100)),
                ('social_media_handles', models.CharField(blank=True, max_length=255)),
                ('publication_address_primary', models.TextField(blank=True)),
                ('publication_address_second', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='publication_logos/')),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
