# Generated by Django 5.2.4 on 2025-09-05 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorhistory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='books.author'),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
        migrations.AddField(
            model_name='bookformat',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookimage',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='books.book'),
        ),
        migrations.AddField(
            model_name='bookparticipant',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
        migrations.AddField(
            model_name='bookparticipant',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='books_authored', through='books.BookParticipant', through_fields=('book', 'author'), to='books.author'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='books.book'),
        ),
        migrations.AddField(
            model_name='chaptercontribution',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='books.chapter'),
        ),
        migrations.AddField(
            model_name='chaptercontribution',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
        migrations.AddField(
            model_name='perpagerate',
            name='paper_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.paperquality'),
        ),
        migrations.AddField(
            model_name='perpagerate',
            name='paper_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.papersize'),
        ),
        migrations.AddField(
            model_name='bookformat',
            name='paper_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.perpagerate'),
        ),
        migrations.AddField(
            model_name='bindingcost',
            name='paper_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.perpagerate'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.publication'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bookparticipant',
            unique_together={('book', 'author', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='perpagerate',
            unique_together={('paper_size', 'paper_quality')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'user')},
        ),
    ]
