# Generated by Django 5.2.11 on 2026-03-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_language_remove_book_language_bookformat_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Black & White, Grayscale, Full Color', max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Printing qualities',
            },
        ),
        migrations.AlterUniqueTogether(
            name='perpagerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='perpagerate',
            name='printing_quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.printingquality'),
        ),
        migrations.AlterUniqueTogether(
            name='perpagerate',
            unique_together={('paper_size', 'paper_quality', 'printing_quality')},
        ),
    ]
