# Generated by Django 5.2.11 on 2026-05-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_printingquality_alter_perpagerate_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorhistory',
            name='department',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
