# Generated by Django 5.2.11 on 2026-05-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_authorhistory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhistory',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
