# Generated by Django 5.2.11 on 2026-06-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_authorhistory_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersize',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='papersize',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bindingcost',
            name='paper_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.papersize'),
        ),
    ]
