# Generated by Django 5.2.11 on 2026-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_papersize_length_papersize_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='book_thumbnails/'),
        ),
    ]
