"""
Django settings for bookstore_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from decouple import config
import pymysql
pymysql.install_as_MySQLdb()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'books.apps.BooksConfig',
    'users.apps.UsersConfig',
    'orders',
    'categories',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'bookstore_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookstore_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config("DB_NAME") or "xoffencer_bookstore", # The name for your database
        'USER': config("DB_USER")or'root',                 # Your MariaDB username (usually 'root')
        'PASSWORD': config("DB_PASS")or'K@rtik@123', # The password you set during installation
        'HOST': '127.0.0.1',            # Or 'localhost'
        'PORT': '3306',                 # The default MariaDB port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'

# --- EMAIL CONFIGURATION (Google Workspace / G Suite) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Use TLS for a secure connection

# Your full Google Workspace email address
EMAIL_HOST_USER = 'info@xoffencerpublication.in' 

# The 16-digit App Password you just generated
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD") 

# This will be the "From" name on the emails
DEFAULT_FROM_EMAIL = f"XOffencer Bookstore <{EMAIL_HOST_USER}>"

SITE_ID = 1

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # The default port for Vite dev server
    "http://localhost:5174", # The default port for Vite dev server
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    'PAGE_SIZE': 20
}

# REST_AUTH = {
#     # This tells the /api/auth/login/ endpoint to use its default, working serializer.
#     'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',

#     # This tells the /api/auth/registration/ endpoint to use its default.
#     'REGISTER_SERIALIZER': 'users.serializers.CustomRegisterSerializer',

#     # This tells ONLY the /api/auth/user/ endpoint to use our custom serializer.
#     # This is what we wanted all along.
#     'USER_DETAILS_SERIALIZER': 'users.serializers.CustomUserDetailsSerializer',
# }


REST_AUTH = {
    'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',
    'REGISTER_SERIALIZER': 'users.serializers.CustomRegisterSerializer',
    'USER_DETAILS_SERIALIZER': 'users.serializers.CustomUserDetailsSerializer',
}

# Media files (user-uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# dj-rest-auth and allauth settings
# ACCOUNT_EMAIL_VERIFICATION = 'none' # Accept accounts without email verification
# ACCOUNT_AUTHENTICATION_METHOD = 'username' # We are logging in with username
# ACCOUNT_EMAIL_REQUIRED = True # Still require an email to be provided

# --- Django-allauth Configuration ---

ACCOUNT_ADAPTER = 'users.adapters.CustomAccountAdapter'

# Allow users to log in using either their username OR their email.
ACCOUNT_AUTHENTICATION_METHOD = 'email'

# An email is required for registration.
ACCOUNT_EMAIL_REQUIRED = True

# The username is required during signup.
ACCOUNT_USERNAME_REQUIRED = False

# Disable email verification for development.
ACCOUNT_EMAIL_VERIFICATION = 'none'


# ACCOUNT_LOGIN_METHODS = {"username", "email" }

ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "username*",
    "password1*",
    "password2*",
]

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


CASHFREE_APP_ID = config("CASHFREE_APP_ID")

CASHFREE_SECRET_KEY = config("CASHFREE_SECRET_KEY")

CASHFREE_PAYOUTS_CLIENT_ID = config("CASHFREE_PAYOUTS_CLIENT_ID")
CASHFREE_PAYOUTS_SECRET_KEY = config("CASHFREE_PAYOUTS_SECRET_KEY")

# --- Delhivery API Settings (Staging/Test Environment) ---
DELHIVERY_API_URL_BASE = "https://track.delhivery.com"

# Endpoint for checking if a pincode is serviced
DELHIVERY_PINCODE_URL = f"{DELHIVERY_API_URL_BASE}/c/api/pin-codes/json/"

# Endpoint for calculating shipping costs
DELHIVERY_SHIPPING_COST_URL = f"{DELHIVERY_API_URL_BASE}/api/kinko/v1/invoice/charges/.json"

DELHIVERY_TOKEN = config("DELHIVERY_TOKEN")
WAREHOUSE_PINCODE = "474009"


# Email address to send new author credentials to
DEFAULT_CREDENTIALS_EMAIL = 'info@xoffencerpublication.in'
