# Generated by Django 5.2.4 on 2025-09-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount'), ('random_range', 'Random Range')], max_length=15)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount value or MIN value for random range', max_digits=10)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, help_text='MAX value for random range (only for that type)', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='The coupon will be valid from this date.', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='The coupon will be invalid after this date.', null=True)),
                ('max_uses', models.PositiveIntegerField(default=100, help_text='The maximum number of times this coupon can be used in total.')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Manually pause or activate the coupon.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('courier', models.CharField(blank=True, choices=[('delhivery', 'Delhivery'), ('dtdc', 'DTDC'), ('bluedart', 'Blue Dart'), ('other', 'Other')], max_length=50, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('transfer_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
