# Generated by Django 5.2.11 on 2026-06-30 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_papersize_length_papersize_width_and_more'),
        ('orders', '0003_alter_cartitem_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.bookformat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='orders.OrderItem', to='books.bookformat'),
        ),
    ]
