# Generated by Django 5.2.11 on 2026-06-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orderitem_book_orderitem_book_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_Methods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
